In [9]:
import pandas as pd
import os 
import seaborn as sns
import matplotlib.pyplot as plt

In [41]:
def get_refinements(df):
    df.Description = df.Description.apply(lambda x: set(x.split(", ")))
    refinements = 0
    for i,row1 in df.iterrows():
        for j, row2 in df.iterrows():
            p1 = row1.Description
            p2 = row2.Description
            q1 = row1.Quality
            q2 = row2.Quality
            # Refinement condition
            if p1 < p2 and q1 >= q2:
                refinements += 1
                # print(f"Refinement found: {p1} -> {p2} with qualities {q1} -> {q2}")
    return refinements

In [42]:
df = pd.DataFrame(columns=["Dataset", "Model", "Refinements"])
for file in os.listdir("./results"):
    if file.endswith(".csv"):
        file_name = file.split(".csv")[0]
        dataset, model = file_name.split("_")
        subgroups = pd.read_csv(os.path.join("./results", file))
        refinements = get_refinements(subgroups)
        df.loc[len(df)] = [dataset, model, refinements]

In [44]:
df.head()

     Dataset       Model  Refinements
0        BSD     Soybean            0
1  SDMapStar    MIMIC-IV            1
2        BSD  Vancomycin            7
3        BSD  Depression            0
4        BSD    connect4          230

In [49]:
df_pivot = df.pivot(index='Dataset', columns='Model', values='Refinements')
display(df_pivot)
print(df_pivot.to_latex(float_format="%.0f"))

Model,Car,Cardio,Chess,Depression,Dermatology,MIMIC-IV,Mushrooms,Soybean,StudentSuccess,Vancomycin,connect4
Dataset,,,,,,,,,,,
BSD,0.0,1.0,0.0,0.0,0.0,3.0,254.0,0.0,182.0,7.0,230.0
SDMapStar,0.0,1.0,NaN,0.0,NaN,1.0,488.0,NaN,NaN,10.0,NaN

\begin{tabular}{lrrrrrrrrrrr}
\toprule
Model & Car & Cardio & Chess & Depression & Dermatology & MIMIC-IV & Mushrooms & Soybean & StudentSuccess & Vancomycin & connect4 \\
Dataset &  &  &  &  &  &  &  &  &  &  &  \\
\midrule
BSD & 0 & 1 & 0 & 0 & 0 & 3 & 254 & 0 & 182 & 7 & 230 \\
SDMapStar & 0 & 1 & NaN & 0 & NaN & 1 & 488 & NaN & NaN & 10 & NaN \\
\bottomrule
\end{tabular}