In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("../dermatology_original.csv")
df.head()

,erythema,scaling,definite_borders,itching,koebner_phenomenon,polygonal_papules,follicular_papules,oral_mucosal_involvement,knee_and_elbow_involvement,scalp_involvement,...,disappearance_granular_layer,vacuolisation_damage_basal_layer,spongiosis,saw_tooth_appearance_retes,follicular_horn_plug,perifollicular_parakeratosis,inflammatory_mononuclear_infiltrate,band_like_infiltrate,age,class
0,2,2,0,3,0,0,0,0,1,0,...,0,0,3,0,0,0,1,0,55,2
1,3,3,3,2,1,0,0,0,1,1,...,0,0,0,0,0,0,1,0,8,1
2,2,1,2,3,1,3,0,3,0,0,...,0,2,3,2,0,0,2,3,26,3
3,2,2,2,0,0,0,0,0,3,2,...,3,0,0,0,0,0,3,0,40,1
4,2,3,2,2,2,2,0,2,0,0,...,2,3,2,3,0,0,2,3,45,3

In [3]:
# Move class column to the beginning
class_col = df.pop('class')
df.insert(0, 'class', class_col)
df.head()

,class,erythema,scaling,definite_borders,itching,koebner_phenomenon,polygonal_papules,follicular_papules,oral_mucosal_involvement,knee_and_elbow_involvement,...,focal_hypergranulosis,disappearance_granular_layer,vacuolisation_damage_basal_layer,spongiosis,saw_tooth_appearance_retes,follicular_horn_plug,perifollicular_parakeratosis,inflammatory_mononuclear_infiltrate,band_like_infiltrate,age
0,2,2,2,0,3,0,0,0,0,1,...,0,0,0,3,0,0,0,1,0,55
1,1,3,3,3,2,1,0,0,0,1,...,0,0,0,0,0,0,0,1,0,8
2,3,2,1,2,3,1,3,0,3,0,...,2,0,2,3,2,0,0,2,3,26
3,1,2,2,2,0,0,0,0,0,3,...,0,3,0,0,0,0,0,3,0,40
4,3,2,3,2,2,2,2,0,2,0,...,2,2,3,2,3,0,0,2,3,45

In [4]:
# Check type and values of each column
for c in df.columns:
    print("Column:", c)
    print("Type:", df[c].dtype)
    print("Number of unique values:", df[c].nunique())

Column: class
Type: int64
Number of unique values: 6
Column: erythema
Type: int64
Number of unique values: 4
Column: scaling
Type: int64
Number of unique values: 4
Column: definite_borders
Type: int64
Number of unique values: 4
Column: itching
Type: int64
Number of unique values: 4
Column: koebner_phenomenon
Type: int64
Number of unique values: 4
Column: polygonal_papules
Type: int64
Number of unique values: 4
Column: follicular_papules
Type: int64
Number of unique values: 4
Column: oral_mucosal_involvement
Type: int64
Number of unique values: 4
Column: knee_and_elbow_involvement
Type: int64
Number of unique values: 4
Column: scalp_involvement
Type: int64
Number of unique values: 4
Column: family_history
Type: int64
Number of unique values: 2
Column: melanin_incontinence
Type: int64
Number of unique values: 4
Column: eosinophils_infiltrate
Type: int64
Number of unique values: 3
Column: PNL_infiltrate
Type: int64
Number of unique values: 4
Column: fibrosis_papillary_dermis
Type: int64
Number of unique values: 4
Column: exocytosis
Type: int64
Number of unique values: 4
Column: acanthosis
Type: int64
Number of unique values: 4
Column: hyperkeratosis
Type: int64
Number of unique values: 4
Column: parakeratosis
Type: int64
Number of unique values: 4
Column: clubbing_rete_ridges
Type: int64
Number of unique values: 4
Column: elongation_rete_ridges
Type: int64
Number of unique values: 4
Column: thinning_suprapapillary_epidermis
Type: int64
Number of unique values: 4
Column: spongiform_pustule
Type: int64
Number of unique values: 4
Column: munro_microabcess
Type: int64
Number of unique values: 4
Column: focal_hypergranulosis
Type: int64
Number of unique values: 4
Column: disappearance_granular_layer
Type: int64
Number of unique values: 4
Column: vacuolisation_damage_basal_layer
Type: int64
Number of unique values: 4
Column: spongiosis
Type: int64
Number of unique values: 4
Column: saw_tooth_appearance_retes
Type: int64
Number of unique values: 4
Column: follicular_horn_plug
Type: int64
Number of unique values: 4
Column: perifollicular_parakeratosis
Type: int64
Number of unique values: 4
Column: inflammatory_mononuclear_infiltrate
Type: int64
Number of unique values: 4
Column: band_like_infiltrate
Type: int64
Number of unique values: 4
Column: age
Type: object
Number of unique values: 61

In [5]:
df["class"].value_counts()

class
1    112
3     72
2     61
5     52
4     49
6     20
Name: count, dtype: int64

In [6]:
# Age is a numeric column, remove it
df = df.drop(columns=['age'])
# Cast columns to str type for subgroup library
for c in df.columns:
    df[c] = df[c].astype(str)
# Save the processed DataFrame
df.to_csv("../dermatology.csv", index=False)

In [7]:
df_train, df_test = train_test_split(df, test_size=0.2, stratify=df["class"], random_state=42)
df_tuning, df_validation = train_test_split(df_train, test_size=0.2, stratify=df_train["class"], random_state=42)
df_train.to_csv("../dermatology_train.csv", index=False)
df_test.to_csv("../dermatology_test.csv", index=False)
df_tuning.to_csv("../dermatology_tuning.csv", index=False)
df_validation.to_csv("../dermatology_validation.csv", index=False)

In [8]:
df.shape

(366, 34)