In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [13]:
df = pd.DataFrame(columns=["Model","Data", "Odds Ratio", "PPV", "k", "Total", "Positive", "Negative"])

for file in os.listdir("./results/"):
    if not file.endswith(".txt") or not file.startswith("BerryFinder_"):
        continue
    file_name = file.split(".txt")[0]
    file_args = file_name.split("_")
    data = file_args[1]
    params = file_args[2].split("-")
    odds_ratio = float(params[0])
    ppv = float(params[1])
    file_path = f"./results/{file}"
    # A 1% coverage threshold was applied for the MIMIC-IV dataset
    if data == "MIMIC-IV":
        file_path = f"./results_BF_low_coverage/{file}"
    with open(file_path, "r") as f:
        lines = f.readlines()
        total = float(lines[0].split(": ")[1])
        positive = float(lines[1].split(": ")[1])
        negative = float(lines[2].split(": ")[1])
        k = int(lines[3].split(": ")[1])
        df.loc[len(df)] = ["BerryFinder", data, odds_ratio, ppv, k, total, positive, negative]

In [14]:
df["Youden's J Index"] = df["Positive"] - df["Negative"]

In [15]:
# df.groupby("Data").agg({"Jaccard": "max"})
# Get k for max Jaccard per Data
df.loc[df.groupby("Data")["Youden's J Index"].idxmax()][["Data", "k"]].set_index("Data").to_dict()["k"]

{'Car': 2,
 'Cardio': 2,
 'Chess': 11,
 'Depression': 2,
 'Dermatology': 147,
 'HealthyAging': 0,
 'MIMIC-IV': 20,
 'Mushrooms': 107,
 'Soybean': 52,
 'StudentSuccess': 83,
 'Vancomycin': 7,
 'connect4': 44}

In [16]:
for d in df["Data"].unique():
    df_d = df[df["Data"] == d]
    df_d = df_d.sort_values(by=["Youden's J Index"], ascending=False)
    df_d[["Odds Ratio", "PPV", "Youden's J Index"]].to_csv("berry_results_csv/"+d+".csv", index=False)
    display(f"Top 10 results for {d} dataset")
    display(df_d.head(10))

'Top 10 results for MIMIC-IV dataset'

,Model,Data,Odds Ratio,PPV,k,Total,Positive,Negative,Youden's J Index
147,BerryFinder,MIMIC-IV,1.8,0.4,20,0.511214,0.955231,0.364886,0.590345
623,BerryFinder,MIMIC-IV,1.2,0.4,20,0.511214,0.955231,0.364886,0.590345
465,BerryFinder,MIMIC-IV,3.0,0.4,20,0.311996,0.686381,0.188616,0.497765
283,BerryFinder,MIMIC-IV,3.0,0.5,20,0.273099,0.612158,0.161360,0.450798
410,BerryFinder,MIMIC-IV,1.8,0.5,20,0.273099,0.612158,0.161360,0.450798
554,BerryFinder,MIMIC-IV,1.2,0.5,20,0.273099,0.612158,0.161360,0.450798
222,BerryFinder,MIMIC-IV,3.0,0.6,19,0.137017,0.347314,0.067712,0.279601
0,BerryFinder,MIMIC-IV,1.2,0.6,19,0.137017,0.347314,0.067712,0.279601
305,BerryFinder,MIMIC-IV,1.8,0.6,19,0.137017,0.347314,0.067712,0.279601
457,BerryFinder,MIMIC-IV,6.0,0.5,6,0.074232,0.208530,0.029974,0.178556

'Top 10 results for Vancomycin dataset'

,Model,Data,Odds Ratio,PPV,k,Total,Positive,Negative,Youden's J Index
4,BerryFinder,Vancomycin,1.2,0.8,7,0.916667,1.0,0.684211,0.315789
13,BerryFinder,Vancomycin,3.0,0.8,6,0.916667,1.0,0.684211,0.315789
74,BerryFinder,Vancomycin,6.0,0.4,3,0.916667,1.0,0.684211,0.315789
179,BerryFinder,Vancomycin,1.8,0.9,28,0.916667,1.0,0.684211,0.315789
162,BerryFinder,Vancomycin,1.2,0.9,28,0.916667,1.0,0.684211,0.315789
157,BerryFinder,Vancomycin,20.0,0.5,3,0.916667,1.0,0.684211,0.315789
110,BerryFinder,Vancomycin,50.0,0.6,2,0.916667,1.0,0.684211,0.315789
107,BerryFinder,Vancomycin,1.8,0.8,7,0.916667,1.0,0.684211,0.315789
266,BerryFinder,Vancomycin,6.0,0.8,3,0.916667,1.0,0.684211,0.315789
228,BerryFinder,Vancomycin,1.8,0.6,7,0.916667,1.0,0.684211,0.315789

'Top 10 results for HealthyAging dataset'

,Model,Data,Odds Ratio,PPV,k,Total,Positive,Negative,Youden's J Index
3,BerryFinder,HealthyAging,1.2,0.50,0,0.0,0.0,0.0,0.0
5,BerryFinder,HealthyAging,1.2,0.95,0,0.0,0.0,0.0,0.0
8,BerryFinder,HealthyAging,3.0,0.60,0,0.0,0.0,0.0,0.0
18,BerryFinder,HealthyAging,1.8,0.60,0,0.0,0.0,0.0,0.0
29,BerryFinder,HealthyAging,3.0,0.40,0,0.0,0.0,0.0,0.0
37,BerryFinder,HealthyAging,1.2,0.40,0,0.0,0.0,0.0,0.0
70,BerryFinder,HealthyAging,12.0,0.90,0,0.0,0.0,0.0,0.0
95,BerryFinder,HealthyAging,6.0,0.95,0,0.0,0.0,0.0,0.0
98,BerryFinder,HealthyAging,6.0,0.80,0,0.0,0.0,0.0,0.0
137,BerryFinder,HealthyAging,50.0,0.50,0,0.0,0.0,0.0,0.0

'Top 10 results for Soybean dataset'

,Model,Data,Odds Ratio,PPV,k,Total,Positive,Negative,Youden's J Index
553,BerryFinder,Soybean,20.0,0.6,52,0.204082,1.0,0.071429,0.928571
196,BerryFinder,Soybean,3.0,0.6,86,0.265306,1.0,0.142857,0.857143
373,BerryFinder,Soybean,6.0,0.6,86,0.265306,1.0,0.142857,0.857143
522,BerryFinder,Soybean,1.8,0.6,86,0.265306,1.0,0.142857,0.857143
540,BerryFinder,Soybean,12.0,0.6,86,0.265306,1.0,0.142857,0.857143
659,BerryFinder,Soybean,1.2,0.6,86,0.265306,1.0,0.142857,0.857143
12,BerryFinder,Soybean,50.0,0.5,37,0.346939,1.0,0.238095,0.761905
288,BerryFinder,Soybean,inf,0.4,126,0.448980,1.0,0.357143,0.642857
217,BerryFinder,Soybean,50.0,0.4,252,0.489796,1.0,0.404762,0.595238
438,BerryFinder,Soybean,20.0,0.5,233,0.510204,1.0,0.428571,0.571429

'Top 10 results for connect4 dataset'

,Model,Data,Odds Ratio,PPV,k,Total,Positive,Negative,Youden's J Index
135,BerryFinder,connect4,1.2,0.8,44,0.714960,0.792710,0.565757,0.226953
86,BerryFinder,connect4,1.8,0.8,44,0.714960,0.792710,0.565757,0.226953
34,BerryFinder,connect4,3.0,0.4,3,0.218614,0.279060,0.102619,0.176440
317,BerryFinder,connect4,3.0,0.8,3,0.218614,0.279060,0.102619,0.176440
509,BerryFinder,connect4,3.0,0.5,3,0.218614,0.279060,0.102619,0.176440
588,BerryFinder,connect4,3.0,0.6,3,0.218614,0.279060,0.102619,0.176440
257,BerryFinder,connect4,1.8,0.6,119,0.910723,0.947931,0.839319,0.108612
68,BerryFinder,connect4,1.8,0.4,119,0.910723,0.947931,0.839319,0.108612
375,BerryFinder,connect4,1.8,0.5,119,0.910723,0.947931,0.839319,0.108612
31,BerryFinder,connect4,1.2,0.6,451,0.999907,1.000000,0.999730,0.000270

'Top 10 results for StudentSuccess dataset'

,Model,Data,Odds Ratio,PPV,k,Total,Positive,Negative,Youden's J Index
532,BerryFinder,StudentSuccess,6.0,0.6,83,0.560734,0.802292,0.325905,0.476387
303,BerryFinder,StudentSuccess,6.0,0.8,83,0.560734,0.802292,0.325905,0.476387
244,BerryFinder,StudentSuccess,1.8,0.8,94,0.625706,0.851003,0.406685,0.444318
629,BerryFinder,StudentSuccess,3.0,0.8,94,0.625706,0.851003,0.406685,0.444318
645,BerryFinder,StudentSuccess,1.2,0.8,94,0.625706,0.851003,0.406685,0.444318
10,BerryFinder,StudentSuccess,6.0,0.9,39,0.218927,0.386819,0.055710,0.331109
102,BerryFinder,StudentSuccess,12.0,0.6,25,0.218927,0.386819,0.055710,0.331109
518,BerryFinder,StudentSuccess,3.0,0.9,39,0.218927,0.386819,0.055710,0.331109
581,BerryFinder,StudentSuccess,12.0,0.9,25,0.218927,0.386819,0.055710,0.331109
508,BerryFinder,StudentSuccess,12.0,0.8,25,0.218927,0.386819,0.055710,0.331109

'Top 10 results for Dermatology dataset'

,Model,Data,Odds Ratio,PPV,k,Total,Positive,Negative,Youden's J Index
171,BerryFinder,Dermatology,inf,0.95,157,0.355932,1.0,0.073171,0.926829
106,BerryFinder,Dermatology,20.0,0.99,147,0.355932,1.0,0.073171,0.926829
91,BerryFinder,Dermatology,inf,0.99,147,0.355932,1.0,0.073171,0.926829
77,BerryFinder,Dermatology,12.0,0.99,147,0.355932,1.0,0.073171,0.926829
351,BerryFinder,Dermatology,inf,0.90,154,0.355932,1.0,0.073171,0.926829
372,BerryFinder,Dermatology,inf,0.80,152,0.355932,1.0,0.073171,0.926829
394,BerryFinder,Dermatology,6.0,0.99,147,0.355932,1.0,0.073171,0.926829
337,BerryFinder,Dermatology,50.0,0.99,147,0.355932,1.0,0.073171,0.926829
440,BerryFinder,Dermatology,3.0,0.99,147,0.355932,1.0,0.073171,0.926829
433,BerryFinder,Dermatology,1.2,0.99,147,0.355932,1.0,0.073171,0.926829

'Top 10 results for Cardio dataset'

,Model,Data,Odds Ratio,PPV,k,Total,Positive,Negative,Youden's J Index
76,BerryFinder,Cardio,1.2,0.4,2,0.252857,0.338217,0.167589,0.170628
483,BerryFinder,Cardio,1.2,0.5,2,0.252857,0.338217,0.167589,0.170628
544,BerryFinder,Cardio,1.2,0.6,2,0.252857,0.338217,0.167589,0.170628
121,BerryFinder,Cardio,3.0,0.4,1,0.118036,0.177416,0.058719,0.118698
314,BerryFinder,Cardio,3.0,0.6,1,0.118036,0.177416,0.058719,0.118698
343,BerryFinder,Cardio,3.0,0.5,1,0.118036,0.177416,0.058719,0.118698
248,BerryFinder,Cardio,1.8,0.4,1,0.118036,0.177416,0.058719,0.118698
282,BerryFinder,Cardio,1.8,0.5,1,0.118036,0.177416,0.058719,0.118698
550,BerryFinder,Cardio,1.8,0.6,1,0.118036,0.177416,0.058719,0.118698
123,BerryFinder,Cardio,20.0,0.9,0,0.000000,0.000000,0.000000,0.000000

'Top 10 results for Depression dataset'

,Model,Data,Odds Ratio,PPV,k,Total,Positive,Negative,Youden's J Index
28,BerryFinder,Depression,6.0,0.6,2,0.604938,0.878049,0.325,0.553049
270,BerryFinder,Depression,6.0,0.5,2,0.604938,0.878049,0.325,0.553049
556,BerryFinder,Depression,6.0,0.4,2,0.604938,0.878049,0.325,0.553049
92,BerryFinder,Depression,3.0,0.6,4,0.716049,0.951220,0.475,0.476220
606,BerryFinder,Depression,3.0,0.4,4,0.716049,0.951220,0.475,0.476220
62,BerryFinder,Depression,3.0,0.5,4,0.716049,0.951220,0.475,0.476220
462,BerryFinder,Depression,1.2,0.8,4,0.419753,0.634146,0.200,0.434146
320,BerryFinder,Depression,1.8,0.8,4,0.419753,0.634146,0.200,0.434146
548,BerryFinder,Depression,3.0,0.8,4,0.419753,0.634146,0.200,0.434146
333,BerryFinder,Depression,12.0,0.6,2,0.271605,0.414634,0.125,0.289634

'Top 10 results for Car dataset'

,Model,Data,Odds Ratio,PPV,k,Total,Positive,Negative,Youden's J Index
16,BerryFinder,Car,3.0,0.60,2,0.559567,0.798969,0.0,0.798969
47,BerryFinder,Car,12.0,0.95,2,0.559567,0.798969,0.0,0.798969
65,BerryFinder,Car,50.0,0.95,2,0.559567,0.798969,0.0,0.798969
79,BerryFinder,Car,6.0,0.60,2,0.559567,0.798969,0.0,0.798969
94,BerryFinder,Car,3.0,0.90,2,0.559567,0.798969,0.0,0.798969
97,BerryFinder,Car,1.2,0.90,2,0.559567,0.798969,0.0,0.798969
105,BerryFinder,Car,50.0,0.40,2,0.559567,0.798969,0.0,0.798969
134,BerryFinder,Car,1.8,0.99,2,0.559567,0.798969,0.0,0.798969
225,BerryFinder,Car,6.0,0.80,2,0.559567,0.798969,0.0,0.798969
146,BerryFinder,Car,1.2,0.95,2,0.559567,0.798969,0.0,0.798969

'Top 10 results for Chess dataset'

,Model,Data,Odds Ratio,PPV,k,Total,Positive,Negative,Youden's J Index
61,BerryFinder,Chess,1.8,0.99,11,0.472656,0.929688,0.015625,0.914062
211,BerryFinder,Chess,1.2,0.99,11,0.472656,0.929688,0.015625,0.914062
172,BerryFinder,Chess,50.0,0.99,11,0.472656,0.929688,0.015625,0.914062
93,BerryFinder,Chess,20.0,0.99,11,0.472656,0.929688,0.015625,0.914062
358,BerryFinder,Chess,12.0,0.99,11,0.472656,0.929688,0.015625,0.914062
530,BerryFinder,Chess,6.0,0.99,11,0.472656,0.929688,0.015625,0.914062
341,BerryFinder,Chess,3.0,0.99,11,0.472656,0.929688,0.015625,0.914062
223,BerryFinder,Chess,50.0,0.80,4,0.486328,0.937500,0.035156,0.902344
315,BerryFinder,Chess,6.0,0.95,7,0.486328,0.937500,0.035156,0.902344
393,BerryFinder,Chess,50.0,0.40,4,0.486328,0.937500,0.035156,0.902344

'Top 10 results for Mushrooms dataset'

,Model,Data,Odds Ratio,PPV,k,Total,Positive,Negative,Youden's J Index
175,BerryFinder,Mushrooms,inf,0.50,107,0.535385,0.998565,0.000000,0.998565
173,BerryFinder,Mushrooms,inf,0.90,107,0.535385,0.998565,0.000000,0.998565
214,BerryFinder,Mushrooms,inf,0.80,107,0.535385,0.998565,0.000000,0.998565
332,BerryFinder,Mushrooms,inf,0.95,107,0.535385,0.998565,0.000000,0.998565
523,BerryFinder,Mushrooms,inf,0.99,107,0.535385,0.998565,0.000000,0.998565
652,BerryFinder,Mushrooms,inf,0.40,107,0.535385,0.998565,0.000000,0.998565
527,BerryFinder,Mushrooms,inf,0.60,107,0.535385,0.998565,0.000000,0.998565
674,BerryFinder,Mushrooms,3.0,0.99,99,0.536923,0.998565,0.003317,0.995249
445,BerryFinder,Mushrooms,1.8,0.99,99,0.536923,0.998565,0.003317,0.995249
357,BerryFinder,Mushrooms,20.0,0.99,99,0.536923,0.998565,0.003317,0.995249